#
# FROM https://github.com/starkandwayne/concourse-tutorial/blob/master/tutorials/basic/task-hello-world/task_hello_world.yml
#
jobs:
  - name: hello-world
    plan:
      - task: say-hello
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: alpine }
          run:
            path: echo
            args: ["Hello, ya'll!"]
