jobs:
  - name: check_docker_engine
    plan:
      - task: check_engine_version
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: docker
              tag: latest
              privileged: true
          params:
            DOCKER_HOST: <IP/hostname>:2375
          run:
            path: docker
            args: ["info"]
