# FROM https://github.com/starkandwayne/concourse-tutorial/blob/master/docker-compose.yml
#
---
version: "3"

services:
  db:
    image: postgres
    networks:
      - net
    environment:
      - POSTGRES_DB=concourse
      - POSTGRES_PASSWORD=concourse_pass
      - POSTGRES_USER=concourse_user
      - PGDATA=/database

  app:
    image: concourse/concourse:latest
    command: quickstart
    networks:
      - net
    privileged: true
    depends_on: [db]
    ports: ["8080:8080"]
    environment:
      - CONCOURSE_POSTGRES_HOST=db
      - CONCOURSE_POSTGRES_USER=concourse_user
      - CONCOURSE_POSTGRES_PASSWORD=concourse_pass
      - CONCOURSE_POSTGRES_DATABASE=concourse
      - CONCOURSE_EXTERNAL_URL
      - CONCOURSE_ADD_LOCAL_USER=admin:admin
      - CONCOURSE_MAIN_TEAM_LOCAL_USER=admin

networks:
  net:
    driver: bridge
